# Generated by Django 6.0 on 2026-03-02 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LibraryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('PDF', 'PDF / E-Book'), ('QUESTION_CURR', 'Question Paper (Current Year)'), ('QUESTION_PREV', 'Question Paper (Previous Year)'), ('NOTES', 'Notes / Study Material'), ('OTHER', 'Other')], default='PDF', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject / Course name', max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Exam year (for question papers)', null=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='library_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='Visible to all approved members')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
